### ISSUE TITLE
getFrequency fails with Python bindings

### ISSUE THREAD

**Issue by xmikos** [pothosware/SoapyUHD#7]
`getFrequency` (for `RF` tunable element) seems to fail with SoapySDR Python bindings. Only SoapyUHD seems to have this problem, every other SoapySDR device I have tried works OK. I can't test this myself, because I don't have USRP device, but one QSpectrumAnalyzer user reported to me this issue xmikos/qspectrumanalyzer#31:

```
Traceback (most recent call last):
  File "/usr/local/bin/soapy_power", line 9, in <module>
    load_entry_point('soapy-power==1.6.0', 'console_scripts', 'soapy_power')()
  File "/usr/local/lib/python3.4/dist-packages/soapy_power-1.6.0-py3.4.egg/soapypower/__main__.py", line 367, in main
  File "/usr/local/lib/python3.4/dist-packages/soapy_power-1.6.0-py3.4.egg/soapypower/power.py", line 296, in sweep
  File "/usr/local/lib/python3.4/dist-packages/soapy_power-1.6.0-py3.4.egg/soapypower/power.py", line 224, in psd
  File "/usr/local/lib/python3.4/dist-packages/SimpleSoapy-1.4.1-py3.4.egg/simplesoapy.py", line 160, in freq
    return self.device.getFrequency(SoapySDR.SOAPY_SDR_RX, self._channel, 'RF')
  File "/usr/lib/python3/dist-packages/SoapySDR.py", line 695, in getFrequency
    def getFrequency(self, *args): return _SoapySDR.Device_getFrequency(self, *args)
RuntimeError: map::at
```

**Comment by guruofquality** [comment]
@xmikos its using the last uhd::tune_result_t from the last time the device was tuned, so I guess on the first run this will fail if an initial freq was never set. Note this is for the specific frequency components and not the overall frequency of the chain. uhd didnt have a way to share just the dsp of just the rf freq, so we had to cache it from the tune result.

Its a work around, but you can try this branch. let me know if that makes sense for your purposes, I will merge it. Im tagging a bunch of stuff this week, so its nice to get anything extra in :-)

* https://github.com/pothosware/SoapyUHD/tree/no_tune_result
* this commit https://github.com/pothosware/SoapyUHD/commit/0542d3e6125e6f3bfad7bec2e622412d55c8ecf5

**Comment by xmikos** [comment]
The problem persist even with *no_tune_result* branch (according to this post: https://github.com/xmikos/qspectrumanalyzer/issues/31#issuecomment-297257798).

**Comment by guruofquality** [comment]
Closing very old issue
